### ISSUE TITLE
Additions to Readme

### ISSUE THREAD

**Issue by monkeychex3** [muschellij2/recordscreen#1]
I was having the below code run successfully half of the time at best.

```
out = start_screen_record(audio = FALSE,
  outfile = tempfile(fileext = ".gif"), verbose = 2)
Sys.sleep(4)
res = end_screen_record(out)
```

 I got it up to working every time by changing the file settings of "ffmpeg.exe" to "run as admin". This seems like a useful tip to put in the readme.md for windows users.

**Comment by muschellij2** [comment]
Can you send a PR?
