### ISSUE TITLE
Cannot make files

### ISSUE THREAD

**Issue by monkeychex3** [muschellij2/recordscreen#2]
A suggestion is, add an example that makes/records a real file. I haven't found any of the `outfile = tempfile()` stuff even where the path from `out$outfile` points me to, as though it doesn't exist.

If I try running a `start_screen_record()` with a real existing file and path, it will get hung up on that line of code and never execute.

I'm sure this is probably something I'm doing wrong, or need to change permissions of something, but I'm out of ideas of where to look.

Got help?

Also, if it matters, I'm running recordscreen version 0.2.0, on R 4.2.2

**Comment by muschellij2** [comment]
Yeah - this doesn't really work for Windows - only *nix versions.  This should produce an output file:
```r
res = Sys.which("ffmpeg")
stopifnot(res != "")
print(list_output_devices())
out = start_screen_record(audio = FALSE, outfile = "output.avi")
Sys.sleep(4)
out
res = end_screen_record(out)
stopifnot(file.exists(out$outfile))
```

So overall, likely not working for Windows.

**Comment by muschellij2** [comment]
Also, if you'd like to make additions, I can incorporate them via a Pull Request, but I'm not working on this project currently.
